version: '3.2'

services:

  grafana:
    build:
      context: ./grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - scaphandre-network

  scaphandre:
    image: hubblo/scaphandre
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
    command: [ "prometheus" ]
    networks:
      - scaphandre-network

  prometheus:
    build:
      context: ./prom
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - promdata-scaphandre:/prometheus
    networks:
      - scaphandre-network

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "4000:80"
    networks:
      - scaphandre-network

  k6:
    build:
      context: ./k6
    networks:
      - scaphandre-network
    env_file:
      - k6/k6.env
    volumes:
      - k6/tests/:/home/k6
    depends_on:
      - scaphandre
      - prometheus
      - fastapi
    ports:
      - "4100:80"
    restart: "no"

  exporter:
    build:
      context: ./exporter
    networks:
      - scaphandre-network
    depends_on:
      k6:
        condition: service_completed_successfully

volumes:
  promdata-scaphandre:


networks:
  scaphandre-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.33.0/24
